[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "./bin/polkadot-latest"
default_args = [ "--log=parachain=debug,xcm=trace,pallet-xcm=trace" ]

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9900

  [[relaychain.nodes]]
  name = "bob"
  validator = true

  [[relaychain.nodes]]
  name = "charlie"
  validator = true

  [[relaychain.nodes]]
  name = "dave"
  validator = true

[[parachains]]
id = 1000
chain = "statemine-local"
cumulus_based = true
add_to_genesis = true

  [parachains.collator]
  name = "statemine-collator01"
  command = "./bin/polkadot-parachain-latest"
  ws_port = 9910
  args = ["--log=xcm=trace,pallet-xcm=trace,pallet-assets=trace"]

[[parachains]]
id = 2000
cumulus_based = true
add_to_genesis = true

  [parachains.collator]
  name = "trappist-collator01"
  command = "./bin/trappist-collator-latest"
  ws_port = 9920
  args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains]]
id = 3000
chain = "penpal-kusama-3000"
cumulus_based = true
add_to_genesis = true

  [parachains.collator]
  name = "collator01"
  command = "./bin/polkadot-parachain-latest"
  ws_port = 9930
  args = ["--log=xcm=trace,pallet-assets=trace"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"

[[hrmp_channels]]
sender = 1000
recipient = 2000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 2000
recipient = 1000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 1000
recipient = 3000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 3000
recipient = 1000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 2000
recipient = 3000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 3000
recipient = 2000
max_capacity = 8
max_message_size = 512
